### ISSUE TITLE
What should the Logsearch favicon be ?

### ISSUE THREAD

**Issue by ryanholder** [logsearch/website#15]
Currently the favicon for Logsearch is the Letter "L" on green background. 

Any ideas on what it should be and if letters is it "L" or "Ls"

**Comment by mrdavidlaing** [comment]
@ryanholder what about the new Kibana elk favicon - ![elasticsearch/kibana/master/src/kibana/styles/theme/elk.ico](https://raw.githubusercontent.com/elasticsearch/kibana/master/src/kibana/styles/theme/elk.ico)

**Comment by ryanholder** [comment]
@mrdavidlaing I think it is a good option for a start.
